Add MakeVisitTableTask to postprocess.py
lsst/pipe_tasks pull request #525
Opened 2021-06-02 14:29 UTC by cmsaunders

2021-06-02 15:52 UTC, erykoff requested changes
Apologies for the drive-by review, but I noticed the quantities used were not self-consistent.

2021-06-02 15:52 UTC, erykoff commented on python/lsst/pipe/tasks/postprocess.py
> +            visitEntry["decl"] = np.mean(visitSummary['decl'])
The position obtained from the mean of all the detectors is not going to be the same as the boresight position.  I'm not sure which one we want, but we need to be consistent.

2021-06-02 15:52 UTC, erykoff commented on python/lsst/pipe/tasks/postprocess.py
> +            azimuth, altitude = visitInfo.getBoresightAzAlt()
The problem here is that the az/alt is going to be inconsistent with the ra/dec above, and that could cause much confusion.  We need to make sure that they are consistent.

2021-06-02 15:52 UTC, erykoff commented on python/lsst/pipe/tasks/postprocess.py
> +            visitEntry["altitude"] = altitude.asRadians()
All units in this table according to the baseline schema should be degrees, e.g. https://github.com/lsst/sdm_schemas/blob/master/yml/baselineSchema.yaml#L5527

2021-06-02 15:52 UTC, erykoff commented on python/lsst/pipe/tasks/postprocess.py
> +            visitEntry["airmass"] = visitInfo.getBoresightAirmass()
Note that the zenith distance in the visit summary table is computed at the center of each ccd.  It is not the boresight zenith distance.  I'm not sure which we want for this table (I personally don't know what "observation mid-point" means technically).  But right now this code snippet will set the zenith distance to the first detector, and the airmass to the boresight.  We need to ensure these are consistent.

Furthermore, "airmass" is a slippery quantity.  There are many ways of computing airmass, and I don't know which one is supposed to be here.  "zenithDistance" is unambiguous, thankfully.

2021-06-12 21:02 UTC, leeskelvin commented on python/lsst/pipe/tasks/postprocess.py
> +    visitSummaries = pipeBase.connectionTypes.Input(
could this just be `connectionTypes`, instead of `pipeBase.connectionTypes`?

2021-06-12 21:16 UTC, leeskelvin approved these changes

2021-06-15 17:35 UTC, merged