DM-34174: Replace PropagateVisitFlagsTask with PropagateSourceFlagsTask
lsst/pipe_tasks pull request #659
Opened 2022-04-05 23:05 UTC by erykoff

2022-04-12 21:02 UTC, fred3m requested changes
Everything looks good with one exception: without having looked at the ticket I wouldn't understand the difference between the source table and the finalized source table, so I think that throughout the PR the docs need to be updated to explain the difference between the two.

I'm also still confused about whether or not it is expected for there to be a scenario where both the source table flags and finalized source table flags are propagated. At least the comments in the default config make it appear as if they won't be regularly used. My recommendation would be to write the entire task to use a single input table and if there is a case where the user will need to propagate both sets of flags, they could run the task twice using different sets of inputs (sources vs finalized sources). Or am I missing something?

2022-04-13 16:54 UTC, erykoff commented on python/lsst/pipe/tasks/finalizeCharacterization.py
> +
I've update the comment that I do this just to be extra sure that information from the input tables doesn't leak through.

2022-04-13 16:55 UTC, erykoff commented on python/lsst/pipe/tasks/finalizeCharacterization.py
> +        """
That was a mistake.  It is not necessary since the names are being carried through from the input catalog.

2022-04-13 17:24 UTC, erykoff commented on python/lsst/pipe/tasks/propagateSourceFlags.py
> +    """Configuration for propagating source flags to coadd objects."""
I think that we decided to leave this as coadd objects vs single-frame sources, right?

2022-04-13 17:31 UTC, erykoff commented on python/lsst/pipe/tasks/propagateSourceFlags.py
> +    )
I've added more documentation to make it clear that there will be a mix of flags from different tables.

2022-04-13 17:39 UTC, fred3m commented on python/lsst/pipe/tasks/propagateSourceFlags.py
> +            self.log.info("Propagated %d finalized sources with flag %s", object_flag.sum(), flag)
Fair enough

2022-04-13 20:00 UTC, fred3m approved these changes

2022-04-14 20:23 UTC, merged