DM-46061: Add Metrics to calibrate task metadata
lsst/pipe_tasks pull request #984
Opened 2024-10-01 17:59 UTC by jrmullaney

2024-10-02 21:53 UTC, isullivan requested changes
Please also add these metadata entries to `calibrateImage`, since we're trying to make the switch to the new task soon.

2024-10-04 08:27 UTC, jrmullaney commented on python/lsst/pipe/tasks/calibrate.py
> +        self.recordFlaggedPixelFractions(exposure)
Given the issues that's happening with `calibrateImage` (see [this slack thread](https://lsstc.slack.com/archives/C2JPMCF5X/p1727991226934669)), I'd prefer to move this to another ticket until those issues have been resolved.

2024-10-04 10:04 UTC, jrmullaney commented
You'll notice that I've also changed how values are written to metadata. It turns out that if one uses the `.add()` method, then it appends to a list of values under that name in the metadata. The catch is that the first value is written as a single-element list, which then gets read as an `ndarray` when the metadata is read-in by the analysis tool. This was the cause of the problem I mentioned on Slack. Using `self.metadata["some_new_metric"] = value` adds `value` as a scalar, rather than a list, which solves the issue.

2024-10-04 22:28 UTC, isullivan approved these changes
Good find about using `self.metadata["some_new_metric"] = value`. I have run into problems with metrics from `self.metadata.add` and this addresses those issues.

I am fine with postponing the additions to `calibrateImage`, but please create that ticket now and link it to DM-43077.

2024-10-06 05:21 UTC, merged